### ISSUE TITLE
here, spmbt.github.io can't load

### ISSUE THREAD

**Issue by blob2015** [spmbt/googleSearchExtraButtons#12]
yeah, so the script is out of work here
besides, hi, guy, will you plan to make a full and independent package, without github.io, since at some regions, the github is not stable

**Comment by spmbt** [comment]
Hi!
Thanks for suggest.
Now, I do not come up with a way to make the availability check of github.io from one common application. If this does not work out, it's need to create two applications: "no memory" (like it was 2 years ago) and "with the memory of settings".

**Comment by blob2015** [comment]
thanks
