### ISSUE TITLE
No functionality...

### ISSUE THREAD

**Issue by mario98** [spmbt/googleSearchExtraButtons#16]
Firefox 60, Greasemonkey 4.4 here and the addon does not work for me. I see no extra buttons. The right sidebar is dimmed though, so the addon is activated. Maybe not compatible with recent Google changes?

**Comment by nevaldiv** [comment]
Im getting the same functionality changes as the above user, and checked the greasyfork page on the script and see that a few people more recently have gotten it too, so it must be that recent google changes have broken it?  Shame, only noticed how much i used it now that its broken.

**Comment by mikhoul** [comment]
Here it work fine I'm using Chromium with Tampermonkey for reference. 

Maybe try Tampermonkey instead of Greasemonkey since GM is well know to have some compatibility issue with older userscripts.

Regards :octocat:

**Comment by spmbt** [comment]
Yes, it may be various occasions; but I may not see any failed cases. Causes may be are: I not live in region in which Google tests another HTML content of search results ( https://greasyfork.org/en/forum/discussion/41970/x ); I not use Mac, where view of input field is different ( https://greasyfork.org/en/forum/discussion/44197 ). Anybody, help to upgrade code : ).
