### ISSUE TITLE
Broken since of today

### ISSUE THREAD

**Issue by mikhoul** [spmbt/googleSearchExtraButtons#17]
This afternoon it stopped working so tonight I've tested more thoroughly on a fresh install with Chromium and latest Tampermonkey with the same results sadly.

I tried especially on google.ca and google.com.au and google.com but it did not work.

I'm not sure but the google search box seem to have changed and seem bigger than before so the underlying code/css must have changed too.

![image](https://user-images.githubusercontent.com/5678673/48655336-7b488b80-e9e3-11e8-91b4-c18fbb3a53af.png)

Let me know if you need more informations to help you to fix it.

Thanks for this useful userscripts. :octocat:

**Comment by luboq** [comment]
+1 https://greasyfork.org/en-US/forum/discussion/46229/x

**Comment by mikhoul** [comment]
[**@waldens**](https://github.com/waldens) commented on [17 nov. 2018 à 10:48 UTC−5](https://github.com/spmbt/googleSearchExtraButtons/issues/17#issuecomment-439626647 "2018-11-17T15:48:46Z - Replied by Github Reply Comments"):
> +1 [https://greasyfork.org/en-US/forum/discussion/46229/x](https://greasyfork.org/en-US/forum/discussion/46229/x)

Yes I've already seen it but I preferred to open the issue here since it's more easy to follow and more suited to follow problems.

I'm pretty sure it will be fixed as soon @spmbt  will see the issue.

Regards :octocat:

**Comment by mikhoul** [comment]
I close it since it was fixed 2 hours ago.

Thanks @spmbt for the quick fix :smile:
