### ISSUE TITLE
Bug in latest version...

### ISSUE THREAD

**Issue by mikhoul** [spmbt/googleSearchExtraButtons#18]
Hi @spmbt ,

The latest version introduced a bug for me: Most of the time when I enter a search term in Google  and press enter it append "**filetype:pdf**" to the query.

Here's a screencast to help you to have a better understanding:  http://screencast-o-matic.com/watch/cFXYetrXUT  

Note: Don't worry with my CSS black theme for Google I will have to adjust it later... 😉

I use Chromium and Tampermonkey.

If you need more information just ask me.

Regards :octocat:

**Comment by spmbt** [comment]
Thanks, I was show this behavior, but for 1st stage was fix main bug with disappear of buttons. Around 1 day I will fix this and disappearing of buttons on the start page.

**Comment by mikhoul** [comment]
It seem to work fine now :smile: 

I don't have the button on the start page but I don't use this feature a lot. :wink: 

Thanks :+1:
