### ISSUE TITLE
Have you committed the latest version on Greasyfork to this repo?

### ISSUE THREAD

**Issue by iam-Shashank** [spmbt/googleSearchExtraButtons#19]
on https://greasyfork.org/en/scripts/7543-google-search-extra-buttons i noticed that it was last updated on 2019-08-13, whereas this repo was updated last in 2018. So, is the latest version on greasyfork proprietary? Great tool btw !

**Comment by spmbt** [comment]
Yes, latest actual version is placed on the Greasyfork account because it have active feedback and installation properties. Version on Github have minor differences. If important changes are required, this version will also be updated.

**Comment by iam-Shashank** [comment]
Ok thanks.
