### ISSUE TITLE
Script seem broken here I don't see any button ?

### ISSUE THREAD

**Issue by mikhoul** [spmbt/googleSearchExtraButtons#20]
Script seem broken here I don't see any button:

![image](https://user-images.githubusercontent.com/5678673/65883167-7d4ddb80-e364-11e9-919d-308521c35274.png)

![image](https://user-images.githubusercontent.com/5678673/65883177-82ab2600-e364-11e9-8561-9a29278c7f91.png)

**Comment by usercase** [comment]
Got the same problem and I fixed it by changing the settings in Firefox : 

1. `Firefox > Settings > Security `
2. Choose `Standard` or `Strict` **(do not choose `Custom`)**

The fact that the dev choose to have a cookie on another domain name (github.io) seems to break Firefo's **Same-origin policy**

Please try and let us know.

**Comment by mrshanepaul** [comment]
Another addon can block it.

For me it was Privacy Badger. Easy to fix in this case, just add spmbt.github.io and google to the exclude list.

I assume other cookie-related addons could do the same thing.

PS: Love the addon. Such a time saver.

**Comment by spmbt** [comment]
(I was answer there: https://greasyfork.org/ru/forum/discussion/63945/x ; problem was due to browser Brave with more high security requirements.)
