### ISSUE TITLE
Overlapping  layout

### ISSUE THREAD

**Issue by elig0n** [spmbt/googleSearchExtraButtons#23]
![image](https://user-images.githubusercontent.com/31196036/76183937-c2f3b780-61d2-11ea-87ae-ddab6f3fad52.png)

Is this where and how the UI should appear ?

**Comment by spmbt** [comment]
Yes, this extra buttons are placed near basic button of search request in all its versions.

**Comment by mikhoul** [comment]
@elig0n    Worst come to worst with extensions like [Stylus](https://github.com/openstyles/stylus) with a little bit of CSS you can customize  the position of the buttons to your own taste. :octocat:
