### ISSUE TITLE
[feature request] add support for encrypted.google.*

### ISSUE THREAD

**Issue by gregist** [spmbt/googleSearchExtraButtons#4]
I use encrypted.google.com a lot because it is arguably [safer](https://security.stackexchange.com/questions/32367/what-is-the-difference-between-https-google-com-and-https-encrypted-google-c), and without annoying regional redirect issues.

**Comment by spmbt** [comment]
Hi!
Thanks for prposition.
```@include     https://encrypted.google.*/search*
was added in https://greasyfork.org/en/scripts/7543-google-search-extra-buttons and here.

**Comment by gregist** [comment]
Cool. Thanks!
