### ISSUE TITLE
Bug in Private tab and with encrypted.google.com

### ISSUE THREAD

**Issue by mikhoul** [spmbt/googleSearchExtraButtons#8]
The Extras button are cramped below the search box:  http://i.imgur.com/KBDobxr.png

Under Firefox 50 with Windows 7

Regards :octocat:

**Comment by spmbt** [comment]
Thank you. This is new layout ща Google search page from 5th of Dec on most usual pages. It was fixed in next revision of code: https://greasyfork.org/en/scripts/7543-google-search-extra-buttons/diff?v1=162739&v2=162657
